# Generated by Django 5.1.6 on 2025-02-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateField(help_text="Task completion date (in the store's time zone)", verbose_name='Date of the task')),
                ('start_time', models.TimeField(help_text="Time when the user started the task (in the store's time zone)", null=True)),
                ('end_time', models.TimeField(help_text="Time when the user completed the task (in the store's time zone)", null=True)),
            ],
        ),
    ]
