# Generated by Django 5.1.6 on 2025-02-13 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_planogram_taskplanogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(max_length=250, null=True, unique=True, verbose_name='Custom ID')),
            ],
        ),
        migrations.CreateModel(
            name='PreScan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_scans', related_query_name='pre_scan', to='app.task')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.scan')),
            ],
        ),
    ]
