# Generated by Django 5.1.6 on 2025-02-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_scan_prescan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planogram',
            name='category',
        ),
        migrations.RemoveField(
            model_name='taskplanogram',
            name='planogram',
        ),
        migrations.RemoveField(
            model_name='prescan',
            name='scan',
        ),
        migrations.RemoveField(
            model_name='prescan',
            name='task',
        ),
        migrations.RemoveField(
            model_name='taskplanogram',
            name='task',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Planogram',
        ),
        migrations.DeleteModel(
            name='Scan',
        ),
        migrations.DeleteModel(
            name='PreScan',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskPlanogram',
        ),
    ]
